#!/bin/bash

## Create new eclipse workspace and copy the settings from the old workspace
## Tomas Kramar, kramar.tomas@gmail.com, 2008
##
## This code is free, you may do whatever you want with it.

FROZEN_DIR=0
OLD_WORKSPACE=~/tools/ECLIPSE_WS_TEMPLATE
WORKSPACE_DIR=/Volumes/Unix/workspaces

function freeze_dir {
    if [[ "$FROZEN_DIR" = "1" ]]; then
        chmod "u-w" $WORKSPACE_DIR
        if [ ! $? ]; then
            echo Could not make "$WORKSPACE_DIR" read-only
            return 1
        fi
    fi
    return 0
}

function die {
    echo $1
    freeze_dir
    exit 1
}


if [ $(whoami) = "root" ]; then
    echo "Don't do this as root"
    exit 1
fi

if [ "$#" = "1" ]; then
    NEW_WORKSPACE=$1;
else
    echo usage: $0 new-workspace
    echo
    echo copies workspace settings from $OLD_WORKSPACE to $WORKSPACE_DIR/new-workspace
    exit 1
fi

if [[ ! ( ( -d "$OLD_WORKSPACE" ) && ( -r "$OLD_WORKSPACE" ) ) ]]; then
    echo $OLD_WORKSPACE is not a readable directory
    exit 1
fi

if [[ ! ( -d "$WORKSPACE_DIR" ) ]]; then
    echo $WORKSPACE_DIR is not a directory
    exit 1
elif [[ ! ( -w "$WORKSPACE_DIR" )  ]]; then
    FROZEN_DIR=1
    chmod u+w "$WORKSPACE_DIR" || die Could not make "$WORKSPACE_DIR" writable
fi

mkdir -p "$WORKSPACE_DIR/$NEW_WORKSPACE" || die Could not create directory $WORKSPACE_DIR/$NEW_WORKSPACE

mkdir -p "$WORKSPACE_DIR/$NEW_WORKSPACE/.metadata/.plugins/org.eclipse.core.runtime/" || die Could not create eclipse settings directory

cp -R "$OLD_WORKSPACE/.metadata/.plugins/org.eclipse.core.runtime/.settings/" "$WORKSPACE_DIR/$NEW_WORKSPACE/.metadata/.plugins/org.eclipse.core.runtime/.settings" || die Could not copy old settings

echo New workspace created. Now start your Eclipse and point it to the $WORKSPACE_DIR/$NEW_WORKSPACE workspace
freeze_dir || exit 1